# Site wide configuration

title: Shehryar Riaz
description: "My personal website. Please excuse the mess, it's a work in progress."
logo: # 120x120 px default image used for Twitter summary card
teaser: teaser-filler.jpg # 400x250 px default teaser image used in image archive grid
locale:
# url: "http://shehryarriaz.com"

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Shehryar Riaz
  email: shehryarriaz@gmail.com
  twitter: osamhain
  google:
    ad-client: 
    ad-slot: 
  bio: "I make things."
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
